config/routes.rb
Rails.application.routes.draw do

  get 'access/index' => 'access#index'

    get 'access/login' => 'access#login'
    get 'access/attempt_login' => 'access#attempt_login'
    post 'access/attempt_login' => 'access#attempt_login'
    get 'access/logout' => 'access#logout'

  root 'access#login'

  resources :users do
    resources :assignments, only: :index
    resources :classrooms, only: :index
  end
  resources :assignments
  resources :classrooms

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :classrooms

  mount_uploader :attachment, AttachmentUploader
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :assignments
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :assignments
  has_and_belongs_to_many :classrooms

  has_secure_password validations: false

  #validates_presence_of :password, :on => :create
  #validates_presence_of :password_confirmation
  #validates_confirmation_of :password

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  def index

  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id


      flash[:notice] = "You are now logged in."
      redirect_to(:action => 'index')
    else
      flash[:notice] = "Invalid username/password combination"
      redirect_to(:action => 'login')
    end
  end

  def logout
    session[:user_id] = nil
    session[:user_id] = nil
    flash[:notice] = "Logged Out"
    redirect_to(:action => "login")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private

  def confirm_logged_in
    unless session[:user_id]
      redirect_to(:controller => 'access', :action => 'login')
      return false
    else
      return true
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(access_index_path) unless @user == current_user
  end

  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  def user_admin
    redirect_to(access_index_path) unless current_user && current_user.admin == true
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  #layout 'default'

  before_action :confirm_logged_in
  before_action :user_admin, except: [:show, :index]
  def index
    @assignments = Assignment.all
  end

  def show
    @assignment = Assignment.find(params[:id])
  end

  def new
    @assignment = Assignment.new
    @users = User.all
  end

  def create
    @assignment = Assignment.new(assignment_params)

    if @assignment.save
      redirect_to assignment_path(@assignment)
    else
      render 'new'
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
    @users = User.all
  end

  def update
    @assignment = Assignment.find(params[:id])

    if @assignment.update_attributes(assignment_params)
      redirect_to assignment_path(@assignment)
    else
      render 'edit'
    end
  end

  def delete
    @assignment = Assignment.find(params[:id])
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy
    redirect_to assignments_path
  end

  private

  def assignment_params
    params.require(:assignment).permit(:title, :content, :due_date, :attachment, :user_ids => [], :classroom_ids => [])
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController

  before_action :confirm_logged_in
  before_action :user_admin, except: [:show, :index]


 # layout 'default'
  def index
    @classrooms = Classroom.all
  end

  def show
    @classroom = Classroom.find(params[:id])#, :include => {:classrooms_users => :user_ids})

  end

  def new
    @classroom = Classroom.new
    @users = User.all
  end

  def create
    @classroom = Classroom.new(classroom_params)

    if @classroom.save
      redirect_to classroom_path(@classroom)
    else
      render 'new'
    end
  end

  def edit
    @classroom = Classroom.find(params[:id])
    @users = User.all
  end

  def update
    @classroom = Classroom.find(params[:id])

    if @classroom.update_attributes(classroom_params)
      redirect_to classroom_path(@classroom)
    else
      render 'edit'
    end
  end

  def delete
    @classroom = Classroom.find(params[:id])
  end

  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy
    redirect_to classrooms_path
  end

  private

  def classroom_params
    params.require(:classroom).permit(:period, :user_ids => [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :correct_user, only: [:edit, :update, :show]
  before_action :confirm_logged_in, :except => [:new, :create]
  before_action :user_admin

#  layout 'default'

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @classrooms = Classroom.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @classrooms = Classroom.all
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :classroom_ids, :password, :password_confirmation, :admin)
  end
end

app/helpers/access_helper.rb
module AccessHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  def user_admin?
    current_user.admin == true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">

    </div>
  </div>
    <div class="col-sm-9">
      Index
    </div>
  </div>
</div>

app/views/access/login.html.erb
<div class="login">
  <%= form_tag(:action => 'attempt_login') do %>
    <table>
      <tr>
        <td><%= label_tag(:username) %></td>
        <td><%= text_field_tag(:username) %></td>
      </tr>
      <tr>
        <td><%= label_tag(:password) %></td>
        <td><%= password_field_tag(:password) %></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><%= submit_tag("Log In") %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/application/_application_sidebar.html.erb
    <div class="col-sm-3">
      <div id="wrapper">

          <!-- Sidebar -->
          <div id="sidebar-wrapper">
              <ul class="sidebar-nav">
                  <%= render partial: 'sidebar' %>
              </ul>
          </div>
      </div>
    </div>

app/views/assignments/_assignment.html.erb
  <div class="row">
    <div class="col-sm-4">
      <h2><%= @assignment.title %></h2>
      <% if @assignment.attachment? %>
        <li>  <%= link_to "Download File", @assignment.attachment.url %></li>
      <% end %>
    </div>
    <div class="col-sm-8">
      <%= @assignment.content %><br>

    </div>
  </div>

app/views/assignments/_form.html.erb
<%= form_for @assignment do |f| %>
<table>
  <tr>
    <th><%= f.label(:title) %></th>
    <td><%= f.text_field(:title) %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:content) %></th>
    <td><%= f.text_area(:content) %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:due_date) %></th>
    <td><%= f.text_field(:due_date, id: "datepicker") %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:attachment) %></th>
    <td><%= f.file_field(:attachment) %></td><br>
  </tr>
  <!--tr>
      <th><%#= f.label(:user_id) %></th>
      <td><%#= f.select(:user_id, @users.map {|s| [s.name, s.id] }) %></td><br>
  </tr-->
  <tr>
    <th>Choose classes to assign: </th>
  </tr>
  <%= f.collection_check_boxes :classroom_ids, Classroom.all, :id, :period do |f| %>

  <tr>
    <td><%= f.check_box %>
       <%= f.label %></td>
    <% end %>
  </tr>
  <tr>
    <td>
      <%= f.submit("Create Assignment", class: 'btn btn-inverse') %>
    </td>
  </tr>



  <!--tr>
    <th>Assign to only these users: </th>
    <%#= f.collection_check_boxes :user_ids, User.all, :id, :name do |f| %>
    <td><%#= f.check_box %>
       <%#= f.label %></td-->
    <%# end %>
  <!--/tr-->



</table>
<% end %>

app/views/assignments/_sidebar.html.erb
<% if user_admin? %>
<li class="sidebar-brand"><%= link_to "New Assignment", new_assignment_path%></li>
<% else %>
  <li class="sidebar-brand">
    Assignments
  </li>
<% end %>
<% @assignments.each do |f| %>
  <li><%= link_to( f.title, assignment_path(f), remote: true) %></li>
  <li><strong>Due Date:</strong><%= f.due_date %></li>
  <% end %>

app/views/assignments/delete.html.erb
<h1>Assignments#delete</h1>
<p>Find me in app/views/assignments/delete.html.erb</p>

app/views/assignments/edit.html.erb
<%= form_for(@assignment) do |f| %>
  <%= render(partial: 'form', locals: {f: f}) %>
  <%= f.submit('Update Assignment') %>
<% end %>

app/views/assignments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div id="wrapper">

          <!-- Sidebar -->
          <div id="sidebar-wrapper">
              <ul class="sidebar-nav">
                  <%= render partial: 'sidebar' %>
              </ul>
          </div>
    </div>
  </div>
    <div class="col-sm-10" id="assignments-show">

    </div>
  </div>
</div>

app/views/assignments/new.html.erb
  <%= render(partial: 'form', locals: {f: @assignment}) %>

app/views/assignments/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h2><%= @assignment.title %></h2>
      <strong>Due Date: </strong><%= @assignment.due_date %>
    </div>
    <div class="col-sm-8">
      <%= @assignment.content %><br>

    </div>
  </div>
</div>

app/views/classrooms/_classroom.html.erb
<h2><%= @classroom.period %></h2>





<% @classroom.assignments.each do |f| %>


      <li><%= link_to f.title, assignment_path(f), remote: true %></li>
      <li><strong>Due: </strong><%= f.due_date %></li>




<% end %>
<% if user_admin? %>
  <h2>Students</h2>
  <% @classroom.users.each do |f| %>

    <table>
      <tr>
        <th>&nbsp;</th>
        <td><%= link_to f.name, user_path(f) %></td>
      </tr>
    </table>
  <% end %>
<% end %>

app/views/classrooms/_form.html.erb
<%= form_for @classroom do |f| %>

<table>
  <tr>

    <td><%= f.text_field(:period, placeholder: "Enter class name...") %></td>
  </tr>

  <tr>
    <th>
      Add students to class:
    </th>
  </tr>
  <%= f.collection_check_boxes :user_ids, User.all, :id, :name do |f| %>
  <tr>
    <td><%= f.check_box %>
  <%= f.label %></td>
      <% end %>

  </tr>
  <tr>
    <td>
      <%= f.submit('Create Classroom', class: 'btn btn-inverse') %>
    </td>
  </tr>


</table>
<% end %>

app/views/classrooms/_sidebar.html.erb
  <% if user_admin? %>
    <li class="sidebar-brand"><%= link_to "New Class", new_classroom_path, remote: true %></li>
  <% else %>
    <li class="sidebar-brand">
      Classes
    </li>
  <% end %>

  <% @classrooms.each do |f| %>
  <li><%= link_to f.period, classroom_path(f), remote: true %></li>
  <% end %>

app/views/classrooms/delete.html.erb
<h1>Classrooms#delete</h1>
<p>Find me in app/views/classrooms/delete.html.erb</p>

app/views/classrooms/edit.html.erb
<%= form_for @classroom do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit("Update Classroom") %>
<% end %>

app/views/classrooms/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div id="wrapper">

          <!-- Sidebar -->
        <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
            <%= render partial: 'sidebar' %>
          </ul>
        </div>
      </div>
    </div>
    <div id="classroom-show" class="col-sm-3">

    </div>
    <div id="assignments-show" class="col-sm-7">

    </div>
  </div>
</div>

app/views/classrooms/new.html.erb
<%= form_for @classroom do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit('Create Classroom') %>
<% end %>

app/views/classrooms/show.html.erb
<strong>Class Period: </strong><%= @classroom.period %>
<h2>Students</h2>
<% @classroom.users.each do |f| %>

  <table>
    <tr>
      <th>&nbsp;</th>
      <td><%= link_to f.name, user_path(f) %></td>
    </tr>
  </table>
<% end %>

<h2>Assignments</h2>
  <table>
    <tr>
      <th>Assignments</th>
      <th>Description</th>
      <th>Due Date</th>
    </tr>
    <% @classroom.assignments.each do |f| %>
    <tr>
      <td><%= link_to f.title, assignment_path(f) %></td>
      <td><%= f.content %></td>
      <td><%= f.due_date %></td>
    </tr>
    <% end %>
  </table>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <li class="navbar-brand active">
        <% if logged_in? %>
          <%= link_to_unless_current "#{current_user.name}", access_index_path %>
        <% else %>
          <a href="#">Classroom Management</a>
          <% end %>
        </li>


    </div>

      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <% if user_admin? %>
            <li class="active"><%= link_to 'Assignments', assignments_path %></li>
            <li class="active"><%= link_to 'Students', users_path %></li>
            <li class="active"><%= link_to 'Classes', classrooms_path %></li>
          <% else %>
            <li class="active"><%= link_to 'Assignments', user_assignments_path(current_user) %></li>
            <li class="active"><%= link_to 'Classes', user_classrooms_path(current_user) %></li>
          <% end %>
          <li class="active"><%= link_to 'Logout', access_logout_path %></li>
        <% end %>
      </ul>

  </div>

</nav>

app/views/layouts/_navigationbak.html.erb
<nav class="navbar navbar-inverse navbar-top">
  <% if logged_in? %>

    <% if user_admin? %>
      <%= link_to_unless_current 'Assignments', assignments_path %>
      <%= link_to_unless_current 'Students', users_path %>
      <%= link_to_unless_current 'Classes', classrooms_path %>

    <% else %>
      <%= link_to_unless_current 'Assignments', user_assignments_path(current_user) %>
      <%= link_to_unless_current 'Classes', user_classrooms_path(current_user) %>
    <% end %>
  <%= link_to "Logout", access_logout_path %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= stylesheet_link_tag '' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'jquery-1.4.2.min.js', 'jquery-ui.min.js' %>

   <!--link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"-->

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navigation' %>

<%= yield %>

</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navigation' %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<table>
  <tr>
    <th><%= f.label(:first_name) %></th>
    <td><%= f.text_field(:first_name) %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name) %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:username) %></th>
    <td><%= f.text_field(:username) %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:password) %></th>
    <td><%= f.password_field(:password) %></td>
  </tr>
  <tr>
    <th><%= f.label(:confirm) %></th>
    <td><%= f.password_field(:password_confirmation) %></td>
  </tr>
  <tr>
    <th><%= f.label(:classroom_ids) %></th>
    <td><%= f.select(:classroom_ids, @classrooms.map {|s| [s.period, s.id] }) %></td><br>
  </tr>
  <tr>
    <th><%= f.label(:admin) %></th>
    <td><%= f.check_box(:admin) %></td>
  </tr>


</table>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit("Update User") %>
<% end %>

app/views/users/index.html.erb
<h1>Students</h1>
<%= link_to "New Student", new_user_path %><br>
<hr>
<% @users.each do |f| %>
  <%= link_to f.name, user_path(f) %><br>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit('Create User', class: 'btn btn-inverse') %>
<% end %>

app/views/users/show.html.erb
<strong><%= @user.name %></strong><br>
<strong>Assignments</strong><br>
<hr>


<table>
  <% @user.classrooms.each do |classroom| %>
    <tr>
      <th>
        <%= link_to classroom.period, classroom_path(classroom) %>

      </th>
    </tr>



    
      <tr>
      <% classroom.assignments.each do |assignment| %>
        <td>
          <%= link_to assignment.title, assignment_path(assignment) %>
        </td>
      </tr>
    <% end %>
  <% end %>


</table>